### ISSUE TITLE
Error when viewing filtered post image

### ISSUE THREAD

**Issue by KurobaExReports** [KurobaExReports/Reports#23]
- Find a post with a picture attached that links or is linked by another post
- Filter the post with "Remove post" action
- Refresh
- Get back to the post you just filtered through another post
- Try to view the attached picture
- Expected: be able to see the picture in fullscreen
- Actual: a toast message appears: "Failed to display viewableMedia (no media to show was found)"

**Comment by K1rakishou** [comment]
>Find a post with a picture attached that links or is linked by another post

Can you please link the post so it's easier to test?

**Comment by KurobaExReports** [comment]
Example post: https://boards.4chan.org/3/thread/874727#p874731

Video: https://files.catbox.moe/lyoh6t.webm

I found it can also be reproduced by manually removing the post

**Comment by K1rakishou** [comment]
Oh I see. The problem here is that the popup reply window is not closed when filter option is clicked.

**Comment by K1rakishou** [comment]
Fixed in https://github.com/K1rakishou/Kuroba-Experimental/commit/0863ab8dfad4296c28ee5635361b131177eb714c

**Comment by KurobaExReports** [comment]
Still reproducible after the update in beta v1.3.3, please reopen

**Comment by K1rakishou** [comment]
You mean the reply chain is not closed when you open filters or that you can't open the image? Because you are not supposed to open it. If you hide/remove a post then it's images are automatically filtered out when you open gallery/media viewer. The current problem here right now is that you can still access the removed post by clicking a quote that points to it which will be fixed in https://github.com/K1rakishou/Kuroba-Experimental/issues/720

**Comment by K1rakishou** [comment]
>The current problem here right now is that you can still access the removed post by clicking a quote that points to it which will be fixed in K1rakishou/Kuroba-Experimental#720

Fixed in https://github.com/K1rakishou/Kuroba-Experimental/commit/da3ac4cfe7970ae6665a4d03d9e71ee452871df0
